apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-ascended-server
  namespace: asa
  labels:
    app: ark-ascended-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ark-ascended-server
  template:
    metadata:
      labels:
        namespace: asa
        app: ark-ascended-server
    spec:
      volumes:
      - name: ark-ascended-server-data
        persistentVolumeClaim:
          claimName: ark-ascended-server-data-pvc
      containers:
      - name: ark-ascended-server
        image: azixus/ark-ascended-docker:latest
        envFrom:
        - configMapRef:
            name: ark-server-config
        resources:
          requests:
            memory: 15Gi
          limits:
            cpu: 2
            memory: 20Gi
        ports:
        - name: server-port
          containerPort: 7790
          protocol: UDP
        - name: rcon-port
          containerPort: 32330
          protocol: TCP
        volumeMounts:
          - name: ark-ascended-server-data
            mountPath:  /opt/arkserver
