apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace}}
spec:
  type: NodePort
  ports:
  - name: server-port
    port: {{ .Values.env.SERVER_PORT }}
    protocol: UDP
    targetPort: {{ .Values.env.SERVER_PORT }}
    nodePort: {{ .Values.service.ports.serverport }} # You can set this to a port within the 30000-32767 range
  - name: rcon-port
    port: {{ .Values.env.RCON_PORT }}
    protocol: TCP
    targetPort: {{ .Values.env.RCON_PORT }}
    nodePort: {{ .Values.service.ports.rconport }} # You can set this to a port within the 30000-32767 range
  selector:
    app: {{ .Release.Name }}