apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace}}
spec:
  type: NodePort
  ports:
  - name: server-port
    port: {{ (index (pluck "value" (where .Values.env "name" "SERVER_PORT")) 0) }}
    protocol: UDP
    targetPort: {{ (index (pluck "value" (where .Values.env "name" "SERVER_PORT")) 0) }}
    nodePort: {{ .Values.service.ports.server-port }} # You can set this to a port within the 30000-32767 range
  - name: rcon-port
    port: {{ (index (pluck "value" (where .Values.env "name" "RCON_PORT")) 0) }}
    protocol: TCP
    targetPort: {{ (index (pluck "value" (where .Values.env "name" "RCON_PORT")) 0) }}
    nodePort: {{ .Values.service.ports.rcon-port }} # You can set this to a port within the 30000-32767 range
  selector:
    app: {{ .Release.Name }}